stages:
  - build
  - test
  - deploy
  - clean
  
build:
  stage: build
  script:
    - ./get_vars.sh
    - terraform init
    - terraform apply -var-file=config.tfvars -auto-approve -target=module.s3_quotes
    - terraform apply -var-file=config.tfvars -auto-approve

test:
  stage: test
  script:
    - ./get_vars.sh
    - pip3 install -e .
    - python3 -m pytest test/test_get_quotes.py
    - python3 -m pytest test/test_html2csv.py
    - python3 -m pytest test/test_clean_quotes.py

deploy:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH != 'master'
  script:
    - 

clean_temp_build:
  stage: clean
  rules:
    - if: $CI_COMMIT_BRANCH != 'master'
  script:
    - terraform destroy -var-file=config.tfvars -auto-approve
