stages:
  - deploy
  - test
  
deploy:
  stage: deploy
  script:
    - ./get_vars.sh
    - terraform init
    - terraform apply -var-file=config.tfvars -auto-approve -target s3_quotes.aws_s3_bucket.main
    - terraform apply -var-file=config.tfvars -auto-approve

test:
  stage: test
  script:
    - ./get_vars.sh
    - python3 -m pytest test