stages:
  - deploy
  - test
  
deploy:
  stage: deploy
  script:
    - ./get_vars.sh
    - terraform init
    - terraform apply -var-file=config.tfvars -auto-approve -target=module.s3_quotes
    - terraform apply -var-file=config.tfvars -auto-approve

test:
  stage: test
  script:
    - ./get_vars.sh
    - pip install -e .
    - python3 -m pytest test